name: Run Python Script

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *" # 8 AM PST/PDT -> 3 PM UTC == 15:00 UTC
    
env:
  FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
  TO_EMAIL: ${{ secrets.TO_EMAIL }}
  PASSWORD: ${{ secrets.PASSWORD }}
  USE_LOCAL: ${{ secrets.USE_LOCAL }}
  SHOULD_SEND_EMAIL: ${{ secrets.SHOULD_SEND_EMAIL }}

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run Python Script
        run: |
          pip install requests
          pip install beautifulsoup4
          python main.py
